### ISSUE TITLE
Panic in RPC Request Handler

### ISSUE THREAD

**Issue by nisdas** [ralexstokes/mev-rs#79]
While testing out the builder subcommand with Prysm we ran into a few panics in the engine-api proxy:

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `params`", line: 1, column: 47)', mev-rs/src/engine_api_proxy/server.rs:110:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `params`", line: 1, column: 47)', mev-rs/src/engine_api_proxy/server.rs:110:79
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `params`", line: 1, column: 47)', mev-rs/src/engine_api_proxy/server.rs:110:79
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `params`", line: 1, column: 47)', mev-rs/src/engine_api_proxy/server.rs:110:79
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `params`", line: 1, column: 47)', mev-rs/src/engine_api_proxy/server.rs:110:79
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `params`", line: 1, column: 47)', mev-rs/src/engine_api_proxy/server.rs:110:79
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `params`", line: 1, column: 47)', mev-rs/src/engine_api_proxy/server.rs:110:79
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `params`", line: 1, column: 47)', mev-rs/src/engine_api_proxy/server.rs:110:79
```
```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: map, expected a string", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:110:79
stack backtrace:
   0:     0x555577ae6eda - std::backtrace_rs::backtrace::libunwind::trace::h79937bc171ada62c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x555577ae6eda - std::backtrace_rs::backtrace::trace_unsynchronized::h2292bca8571cb919
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x555577ae6eda - std::sys_common::backtrace::_print_fmt::h9c461f248e4ae90d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x555577ae6eda - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he9fe6bf1a39182e1
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x555577b0943e - core::fmt::write::h032658c119c720d7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/fmt/mod.rs:1208:17
   5:     0x555577ae1d55 - std::io::Write::write_fmt::h299fc90dfae41c0d
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/io/mod.rs:1682:15
   6:     0x555577ae6ca5 - std::sys_common::backtrace::_print::heb70d25df9937e3f
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x555577ae6ca5 - std::sys_common::backtrace::print::had745c0a76b8b521
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x555577ae848f - std::panicking::default_hook::{{closure}}::h1ea782cdfa2fd097
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:267:22
   9:     0x555577ae81cb - std::panicking::default_hook::h1cc3af63455a163c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:286:9
  10:     0x555577ae8b9c - std::panicking::rust_panic_with_hook::h5cafdc4b3bfd5528
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:688:13
  11:     0x555577ae8939 - std::panicking::begin_panic_handler::{{closure}}::hf31c60f40775892c
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:579:13
  12:     0x555577ae738c - std::sys_common::backtrace::__rust_end_short_backtrace::h28a5c7be595826cd
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x555577ae8642 - rust_begin_unwind
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/panicking.rs:575:5
  14:     0x555577194ed3 - core::panicking::panic_fmt::h8fa27a0b37dd98b7
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/panicking.rs:64:14
  15:     0x555577195363 - core::result::unwrap_failed::h62abf61e411aaa08
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/core/src/result.rs:1791:5
  16:     0x555577681f0b - mev_rs::engine_api_proxy::server::Proxy::process_message::{{closure}}::h560197097207f107
  17:     0x55557767b0bd - <F as axum::handler::Handler<(M,T1,T2),S,B>>::call::{{closure}}::h09b4586a8f081bf8
  18:     0x555577627e94 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::hb61c9d96057766ee
  19:     0x555577628a00 - <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll::heef8fc288e3c7743
  20:     0x555577588e69 - <tower::util::map_response::MapResponseFuture<F,N> as core::future::future::Future>::poll::h1fc043635f66677a
  21:     0x555577620c82 - <tower::util::oneshot::Oneshot<S,Req> as core::future::future::Future>::poll::h286702d4ade207c3
  22:     0x55557763c347 - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_loop::habf9946edf1ea427
  23:     0x5555776351cd - hyper::proto::h1::dispatch::Dispatcher<D,Bs,I,T>::poll_catch::ha2cd3d3a1c2c7a45
  24:     0x5555776a542f - <hyper::server::conn::upgrades::UpgradeableConnection<I,S,E> as core::future::future::Future>::poll::h96450b2423008ba3
  25:     0x5555775a760a - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::h57605bd19c4603e0
  26:     0x55557769f63b - tokio::runtime::task::core::Core<T,S>::poll::h8071d8e0c71e39ab
  27:     0x5555776618d6 - tokio::runtime::task::harness::Harness<T,S>::poll::haf4a4708eb2fd2ad
  28:     0x555577a59e63 - tokio::runtime::scheduler::multi_thread::worker::Context::run_task::h8d4f24be8de64b04
  29:     0x555577a590a3 - tokio::runtime::scheduler::multi_thread::worker::Context::run::h442a977413f60eef
  30:     0x555577a498d9 - tokio::macros::scoped_tls::ScopedKey<T>::set::h801ae329571976b6
  31:     0x555577a58e01 - tokio::runtime::scheduler::multi_thread::worker::run::hf25109b2855f4381
  32:     0x555577a42382 - tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut::hd72c42c438a87d77
  33:     0x555577a6169c - tokio::runtime::task::core::Core<T,S>::poll::h42de8c006a2c4308
  34:     0x555577a6058f - tokio::runtime::task::harness::Harness<T,S>::poll::h0a107b481e3cd43a
  35:     0x555577a4b5b2 - tokio::runtime::blocking::pool::Inner::run::hc24a4ef215364a9d
  36:     0x555577a4bb48 - std::sys_common::backtrace::__rust_begin_short_backtrace::h5ff66ddc3cb2ad9a
  37:     0x555577a548fb - core::ops::function::FnOnce::call_once{{vtable.shim}}::h60dd651b51e8b0d7
  38:     0x555577aeb583 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hb77d8d72ebcf79c4
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  39:     0x555577aeb583 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::hc08c3353e1568487
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/alloc/src/boxed.rs:2000:9
  40:     0x555577aeb583 - std::sys::unix::thread::Thread::new::thread_start::h7168e596cd5e5ce6
                               at /rustc/d5a82bbd26e1ad8b7401f6a718a9c57c96905483/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7fea119c9b43 - start_thread
                               at ./nptl/./nptl/pthread_create.c:442:8
  42:     0x7fea11a5ba00 - clone3
                               at ./misc/../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
  43:                0x0 - <unknown>
  ```
  It appears that the proxy has difficulties in handling errors here. The specific json-rpc requests for which this was triggered was  for
  ```
  eth_chainId
  ```
  and a batch request for `eth_getBlockByNumber`

**Comment by nisdas** [comment]
This is another one that i receive in `GetPayload`

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Error("expected value", line: 1, column: 1)', mev-rs/src/engine_api_proxy/server.rs:121:85
```

**Comment by ralexstokes** [comment]
thanks for this! I have only tested w/ lighthouse and perhaps prysm is using more/different features from JSON-RPC that the engine proxy doesn't support yet

will debug soon :)

**Comment by ralexstokes** [comment]
after #112, there is a new take on the builder design that just directly integrates with `reth` as an execution client

this direct integration should remove this entire class of bugs around managing the engine API and moreover I have removed that code entirely

so I'm going to close this, thanks for the report :)
